'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SystemManage_SpcProcedure
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Callback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Callback As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''PolNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''OrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''EndNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LoadNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''CustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''CustNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''IssuDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IssuDate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tmpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tmpdate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''CoverFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoverFrom As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''CoverTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoverTo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''Refund control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Refund As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''SerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerialNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''RefundFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefundFrom As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''OldPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldPolicy As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''NETPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NETPRM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Currency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Currency As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''lastNet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastNet As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TAXPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TAXPRM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Exchange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exchange As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PayType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CONPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CONPRM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Cur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cur As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''STMPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STMPRM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ISSPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ISSPRM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''OKRefund control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OKRefund As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''Br control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Br As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TOTPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TOTPRM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OK As Global.DevExpress.Web.ASPxButton
End Class
