'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DistPolicy

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ASPxRoundPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel1 As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''AlertL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertL As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''PolNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolNo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''EndNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndNo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''LoadNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadNo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''GoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoBack As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''IssuDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IssuDate As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SumInsured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SumInsured As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''NetPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetPRM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Comission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Comission As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CoverFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoverFrom As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''HNetPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HNetPRM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CoverTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoverTo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''HDistNet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDistNet As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''DistNet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DistNet As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''War control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents War As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''HWar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HWar As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Exc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exc As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''HF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''DistWar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DistWar As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SpRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpRet As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''WSpRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WSpRet As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''HFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''FacRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FacRatio As Global.DevExpress.Web.ASPxTrackBar

    '''<summary>
    '''WarFacRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WarFacRatio As Global.DevExpress.Web.ASPxTrackBar

    '''<summary>
    '''SpRetRatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpRetRatio As Global.DevExpress.Web.ASPxTrackBar

    '''<summary>
    '''ASPxRoundPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel2 As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''TreatyNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreatyNo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CustName0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustName0 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''EndCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndCnt As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TSumIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TSumIns As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CustNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustNo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TOTPRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TOTPRM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Cur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cur As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Capacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Capacity As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Ret control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ret As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''QS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QS As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''FirstSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstSup As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SecondSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondSup As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''LineSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LineSlip As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Fac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fac As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TRQSRCOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRQSRCOM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TR1STCOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR1STCOM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TR2STCOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR2STCOM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TRLSCOMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRLSCOMM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''FacComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FacComm As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TSpRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TSpRet As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TRWQSRCOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRWQSRCOM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TRW1STCOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRW1STCOM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRet As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''wFac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wFac As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TNetPrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TNetPrm As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TQS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TQS As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''wQS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wQS As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TSecondSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TSecondSup As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxButton5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton5 As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''TFac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TFac As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TLineSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TLineSlip As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TFirstSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TFirstSup As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''wFirstSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wFirstSup As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''AlertL0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertL0 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ExtPrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtPrm As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton3 As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton4 As Global.DevExpress.Web.ASPxButton
End Class
