'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MarineCargoOC
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Callback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Callback As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''PolicyControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PolicyControl As Global.PolicyControl

    '''<summary>
    '''Importer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Importer As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ContractNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContractNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Loads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Loads As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''InvNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Quantity As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''UnitPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitPrice As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''SurNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SurNo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Bank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bank As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''BankCommision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankCommision As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''DocVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocVal As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Currency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Currency As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ExcRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExcRate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''SumIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SumIns As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''NewSumIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewSumIns As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Margin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Margin As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''RespVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RespVal As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''MarBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarBy As Global.DevExpress.Web.ASPxTokenBox
    
    '''<summary>
    '''ShipNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipNo As Global.DevExpress.Web.ASPxGridLookup
    
    '''<summary>
    '''TripFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TripFrom As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TripTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TripTo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TripFromTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TripFromTo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''GodCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GodCat As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''GodType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GodType As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''FillType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FillType As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''InsCond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsCond As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''SpcCond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpcCond As Global.DevExpress.Web.ASPxTokenBox
    
    '''<summary>
    '''btnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShow As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''Distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Distance As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''GodArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GodArrival As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''WarCover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WarCover As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''MarRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarRate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''MarPrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarPrm As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ReLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReLoad As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''ShipRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipRate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ShipPrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipPrm As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''OutLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OutLoad As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''ExtraRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraRate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ExtraPrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraPrm As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''WarRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WarRate As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''WarPrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WarPrm As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''Ships control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ships As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Condss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Condss As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''InsConds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsConds As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sCondss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sCondss As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''MarB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarB As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Banks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Banks As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Cur1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cur1 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
