'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Policy_Default

    '''<summary>
    '''Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''notificationTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notificationTimer As Global.DevExpress.Web.ASPxTimer

    '''<summary>
    '''Reports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reports As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmbReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReports As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''Branch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Branch As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Sys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sys As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''MainGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainGrid As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Print As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''Renew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Renew As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''Issuance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Issuance As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''CreditNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreditNote As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''Payment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payment As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''DebitNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DebitNote As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''RequestCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestCancel As Global.DevExpress.Web.GridViewCommandColumnCustomButton

    '''<summary>
    '''Popup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Popup As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''pcConfirmDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcConfirmDelete As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''yesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''noButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''pcConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcConfirmIssue As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''yesIssButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesIssButton As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''noIssButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noIssButton As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''SqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceLog As Global.System.Web.UI.WebControls.SqlDataSource
End Class
